FROM cirrusci/flutter:stable as builder

WORKDIR /build

COPY . /build/.

RUN flutter pub get
RUN flutter build web --release

FROM nginx:1.21.4-alpine

COPY --from=builder /build/build/web /usr/share/nginx/html


