FROM cirrusci/flutter:stable as builder

WORKDIR /build

COPY . /build/.

RUN flutter pub get
RUN flutter build web --release

FROM nginx:1.22.0

COPY --from=builder /build/build/web /usr/share/nginx/html
COPY scripts/bake_env.sh .
ENV OPENSIGHT_CORE_URL "localhost:28019"

CMD [  "bash", "bake_env.sh", "&&", "nginx", "-g", "daemon off" ]