FROM cirrusci/flutter:stable as builder

WORKDIR /build

COPY . /build/.

RUN flutter pub get
RUN flutter build web --release

FROM nginx:1.22.0

COPY --from=builder /build/build/web /var/www/dashboard
COPY scripts/bake_env.sh .
RUN rm /etc/nginx/conf.d/default.conf
COPY scripts/nginx.conf /etc/nginx/conf.d/dashboard.conf
ENV OPENSIGHT_CORE_URL "localhost:28019"
RUN chmod 755 /bake_env.sh

CMD [ "/bake_env.sh" , "nginx", "-g", "daemon off;"]