FROM rust:1.54.0 as builder
ENV USER root
WORKDIR /core
COPY . /core/.
RUN rustup default nightly
RUN rustup update
RUN cargo build --release

FROM ubuntu:21.04
RUN apt update && apt install postgresql-client -y
COPY --from=builder /core/target/release/opensight_core opensight_core
RUN useradd -u 8877 notroot

RUN mkdir -p /var/log/opensight/
RUN chmod -R 777 /var/log/opensight

USER notroot
CMD ["./opensight_core"]