FROM rust:1.58.1 as builder
ENV USER root
WORKDIR /core
COPY . /core/.
RUN rustup default nightly
RUN rustup update
RUN cargo build --release

FROM ubuntu:21.04
RUN apt update && apt install postgresql-client -y && apt install wget -y
COPY --from=builder /core/target/release/opensight_core opensight_core
COPY scripts/bake_conf.sh .
RUN useradd -u 8877 notroot

RUN mkdir -p /var/log/opensight/
RUN chmod -R 777 /var/log/opensight
ENV RUST_LOG=debug
USER notroot

CMD ["/bake_conf.sh", "./opensight_core"]
