FROM rust:1.40 as builder
ENV USER root
COPY . .
WORKDIR analytics_api
RUN rustup install nightly
RUN cargo update
RUN cargo build --release

FROM alpine
COPY --from=builder /analytics_api/target/release/analytics_api /analytics_api
CMD ["/analytics_api"]