FROM rust:1.54.0 as builder
ENV USER root
WORKDIR analytics_api
COPY . .
RUN rustup default nightly
RUN rustup update
RUN cargo build --release

FROM debian:buster-slim
RUN apt-get update && apt upgrade -y && rm -rf /var/lib/apt/lists/*
COPY --from=builder /analytics_api/target/release/analytics_api /usr/lokal/bin/analytics_api
CMD ["/analytics_api"]