FROM rust:1.58.1 as builder
ENV USER root
WORKDIR /analytics_api
COPY . .
RUN rustup default nightly
RUN rustup update
RUN cargo build --release

FROM ubuntu:21.04
RUN apt update && apt install postgresql-client -y
COPY --from=builder /analytics_api/target/release/opensight_analytics_api opensight_analytics_api
COPY scripts/bake_conf.sh .
RUN chmod 755 /bake_conf.sh

#RUN useradd -u 8877 notroot

RUN mkdir -p /var/log/opensight/
RUN chmod -R 777 /var/log/opensight
ENV RUST_LOG=debug
#USER notroot

CMD ["/bake_conf.sh", "./opensight_analytics_api"]
